services:
  # vortex-pg:
  #   image: bitnami/postgresql:latest
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     - POSTGRES_USER=docker
  #     - POSTGRES_PASSWORD=docker
  #     - POSTGRES_DB=vortex
  #   volumes:
  #     - ./docker:/docker-entrypoint-initdb.d

  vortex-jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686" # Jaeger UI
      - "6831:6831/udp" # UDP for traces
      - "14268:14268" # HTTP for traces (OTLP/HTTP)
      - "4317:4317" # OTLP/gRPC
      - "4318:4318" # OTLP/HTTP